services:
  - type: web
    name: mytelegrambot2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_webhook.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
